# Ejercicio de Ciencia de Datos con NumPy
A continuación, se presenta el paso a paso de los ejercicios con NumPy. Cada sección incluye una explicación en Markdown y el código correspondiente.

### 1. Importar NumPy
Primero, se importa la biblioteca NumPy, ya que proporciona funciones para trabajar con arrays y matrices numéricas.

In [16]:
import numpy as np

### 2. Crear un array del 1 al 100
Se usa np.arange() para generar un array con números consecutivos del 1 al 100.

In [17]:
# Crear un array del 1 al 100
array_inicial = np.arange(1, 101)
print("Array inicial (1-100):\n", array_inicial)

Array inicial (1-100):
 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


## Explicación:
np.arange(1, 101) genera valores desde 1 (incluido) hasta 101 (no incluido), es decir, del 1 al 100.

### 3. Convertir el array en una matriz 10x10
se usa .reshape() para transformar el array unidimensional en una matriz bidimensional de 10 filas × 10 columnas.

In [18]:
# Cambiar la forma a una matriz 10x10
matriz_10x10 = array_inicial.reshape(10, 10)
print("\nMatriz 10x10:\n", matriz_10x10)


Matriz 10x10:
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


###Explicación:

.reshape(10, 10) reorganiza los 100 elementos en una estructura de 10 filas y 10 columnas.

Si el tamaño no coincide (ej: reshape(5, 20)), aparecerá un error.

### 4. Calcular la media de todos los elementos
se usa np.mean() para obtener el promedio de todos los valores en la matriz.

In [19]:
# Calcular la media
media = np.mean(matriz_10x10)
print("\nMedia de todos los elementos:", media)


Media de todos los elementos: 50.5


### 5. Calcular la suma total de los elementos
Usamos np.sum() para sumar todos los elementos de la matriz.
(fórmula de Gauss: n(n+1)/2).

In [20]:
# Calcular la suma total
suma_total = np.sum(matriz_10x10)
print("Suma total de los elementos:", suma_total)

Suma total de los elementos: 5050


### 6. Obtener la diagonal principal de la matriz
Usamos np.diag() para extraer los elementos de la diagonal principal.

In [21]:
# Obtener la diagonal principal
diagonal_principal = np.diag(matriz_10x10)
print("\nDiagonal principal:\n", diagonal_principal)


Diagonal principal:
 [  1  12  23  34  45  56  67  78  89 100]


### 7. Filtrar elementos mayores a 50
Usamos indexación booleana para seleccionar solo los valores mayores a 50.


In [22]:
# Obtener elementos mayores a 50
elementos_mayores_50 = matriz_10x10[matriz_10x10 > 50]
print("\nElementos mayores a 50:\n", elementos_mayores_50)


Elementos mayores a 50:
 [ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


## Explicación:

matriz_10x10 > 50 crea una máscara booleana (True/False).

Al aplicarla como índice (matriz_10x10[condición]), solo se devuelven los valores donde la condición es True.